### ISSUE TITLE
Tab Content padding

### ISSUE THREAD

**Issue by yapcheahshen** [Theadd/react-panels#18]
Please recommend a good approach to change tab content padding (now is 10px ) without creating new theme.

**Comment by Theadd** [comment]
Well, sorry for the delay but I've a demonstration at work in a few days which is killing me =D

It could be done the right way, which I can't see at the moment, or it could be done in a **dirty** and incredible simple way:

``` css
.tab-content {
  padding: 50px !important;
}
```
